{{- if .Values.azuredisk.useV2Driver -}}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azvolumeattachments.disk.csi.azure.com
spec:
  group: disk.csi.azure.com
  names:
    kind: AzVolumeAttachment
    listKind: AzVolumeAttachmentList
    plural: azvolumeattachments
    singular: azvolumeattachment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Name of the Node which this AzVolumeAttachment object is attached to
      jsonPath: .spec.nodeName
      name: NodeName
      type: string
    - description: Name of the Volume which this AzVolumeAttachment object references
      jsonPath: .spec.underlyingVolume
      name: UnderlyingVolume
      type: string
    - description: Indicates if the volume attachment should be primary attachment or not
      jsonPath: .spec.role
      name: RequestedRole
      type: string
    - description: Indicates if the volume attachment is primary attachment or not
      jsonPath: .status.role
      name: Role
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AzVolumeAttachment is a specification for a AzVolumeAttachment resource
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of a AzVolumeAttachment. Required.
            properties:
              nodeName:
                type: string
              role:
                description: Role indicates if the volume attachment is replica attachment or not
                type: string
              underlyingVolume:
                type: string
            required:
            - nodeName
            - role
            - underlyingVolume
            type: object
          status:
            description: status represents the current state of AzVolumeAttachment. Nil status indicates that the underlying volume of AzVolumeAttachment has not yet been attached to the specified node
            properties:
              role:
                description: Role indicates if the volume attachment is replica attachment or not
                type: string
            required:
            - role
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
{{- end -}}