{{- if .Values.azuredisk.useV2Driver -}}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azvolumes.disk.csi.azure.com
spec:
  group: disk.csi.azure.com
  names:
    kind: AzVolume
    listKind: AzVolumeList
    plural: azvolumes
    singular: azvolume
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AzVolume is a specification for a AzVolume resource
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          spec:
            description: AzVolumeSpec is the spec for a AzVolume resource
            properties:
              name:
                description: The suggested name for the storage space
                type: string
              volumeCapability:
                description: The capabilities that the volume MUST have
                type: object              
              underlyingVolume:
                format: int32
                type: integer
              maxMountReplicaCount:
                type: integer
              parameters:
                type: object
            required:
            - underlyingVolume
            - name
            - volumeCapability
            type: object
          status:
            description: AzVolumeStatus is the status for a AzVolume resource. Nil indicates that the underlying volume of AzVolumeAttachment has not yet been attached to the specific node
            properties:
              state:
                description: Indicates the current state
                type: string
              underlyingVolume:
                format: int32
                type: integer
            required:
            - state
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
{{- end -}}