apiVersion: v1
entries:
  azuredisk-csi-driver:
  - apiVersion: v1
    appVersion: v2.0.0-alpha.1
    created: "2021-06-25T22:03:15.0189953Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 59b35f0b072d92d0825604592b1d65c7ab4c91862b01c4bacd22aef699e6a293
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v2.0.0-alpha.1/azuredisk-csi-driver-v2.0.0-alpha.1.tgz
    version: v2.0.0-alpha.1
  - apiVersion: v1
    appVersion: latest
    created: "2021-06-25T22:03:15.0022853Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: e0555d0b965280de9607faa8ed3e177c64e5c9a937eb09c0e6db33697ecf3918
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/latest/azuredisk-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2021-06-25T22:03:15.0176492Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 55e5e17aac7c144b21a198867654ef70ad272987b0bb165782905adf91ca3c03
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.4.0/azuredisk-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2021-06-25T22:03:15.0164124Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 2665483e922a577feb8539ca7f774bc70c945ce490294fd3378f098c2d244dde
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.3.0/azuredisk-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2021-06-25T22:03:15.0149038Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 2bbfe2f9d080f1b3ff10590c7168d05ce026c5a73332b4d48014610a52337808
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.2.0/azuredisk-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.1
    created: "2021-06-25T22:03:15.0129203Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: dd7066be8f499f6c1a396ab27c0013c09f5a8d8319cc04fbdd480d31107bb851
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.1.1/azuredisk-csi-driver-v1.1.1.tgz
    version: v1.1.1
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2021-06-25T22:03:15.0109679Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 3d2a5189416dd6a43bd3e2097bbe23a8db347b6e1a36c6a43fd59cc9c9633ff3
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.1.0/azuredisk-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2021-06-25T22:03:15.0096662Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: d179bc6f338518859b6efdc3b3bed8d06513313e8047563eb4b654b2d417c81e
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v1.0.0/azuredisk-csi-driver-v1.0.0.tgz
    version: v1.0.0
  - apiVersion: v1
    appVersion: v0.10.0
    created: "2021-06-25T22:03:15.0035272Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 3dbbaca098fe8316de079236598253b5831e8e85fd88b390231d828157d62206
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.10.0/azuredisk-csi-driver-v0.10.0.tgz
    version: v0.10.0
  - apiVersion: v1
    appVersion: v0.9.0
    created: "2021-06-25T22:03:15.0083837Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: a978f3e6ef5d678c3b6512bd8a63277cb4ce40d3f3e34b80370f0c37298824f2
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.9.0/azuredisk-csi-driver-v0.9.0.tgz
    version: v0.9.0
  - apiVersion: v1
    appVersion: v0.8.0
    created: "2021-06-25T22:03:15.0072194Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 1762b832389b4f7a5eab9748127fa6dbb85131485d67bc3fe485bbe86c468128
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.8.0/azuredisk-csi-driver-v0.8.0.tgz
    version: v0.8.0
  - apiVersion: v1
    appVersion: v0.7.0
    created: "2021-06-25T22:03:15.0057239Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 29e21f686814f46c1edaaaa95ce2d25579ff1aad270c58b774bdb5a89858b8bf
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.7.0/azuredisk-csi-driver-v0.7.0.tgz
    version: v0.7.0
  - apiVersion: v1
    appVersion: v0.6.0
    created: "2021-06-25T22:03:15.0045165Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: b11d8dfee371ca7c63a1448ba27c1fd1f032ea33575fefeeb16927fc95d1eeb7
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/abhisheksinghbaghel/azuredisk-csi-driver/master/charts/v0.6.0/azuredisk-csi-driver-v0.6.0.tgz
    version: v0.6.0
generated: "2021-06-25T22:03:14.9995836Z"
